CREATE DATABASE OOP_gca2;
USE DATABASE OOP_gca2;

-- user account, if not confirmed / confirm if it works
CREATE USER 'OOP_gca2_user'@'localhost' IDENTIFIED VIA mysql_native_password USING '***';GRANT ALL PRIVILEGES ON *.* TO 'OOP_gca2_user'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `OOP\_gca2`.* TO 'OOP_gca2_user'@'localhost';

CREATE TABLE location (
     id INT AUTO_INCREMENT PRIMARY KEY,
     latitude DECIMAL(10, 8) NOT NULL,
     longitude DECIMAL(11, 8) NOT NULL,
     full_address VARCHAR(255),
     created_at DATETIME NOT NULL
 );

 CREATE TABLE route_stop (
     id INT AUTO_INCREMENT PRIMARY KEY,
     route_name VARCHAR(100) NOT NULL,
     location_id INT NOT NULL,
     created_at DATETIME NOT NULL,
     FOREIGN KEY (location_id) REFERENCES location(id)
 );

 CREATE TABLE trail (
     id INT AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(100) NOT NULL,
     description TEXT,
     difficulty ENUM('Easy', 'Moderate', 'Hard') NOT NULL,
     estimated_time DECIMAL(5,2)
 );

 CREATE TABLE trail_stop (
     trail_id INT NOT NULL,
     stop_id INT NOT NULL,
     PRIMARY KEY (trail_id, stop_id),
     FOREIGN KEY (trail_id) REFERENCES trail(id),
     FOREIGN KEY (stop_id) REFERENCES route_stop(id)
 );

 CREATE TABLE trail_media (
     id INT AUTO_INCREMENT PRIMARY KEY,
     trail_id INT NOT NULL,
     stop_id INT NULL,
     media_type ENUM('IMAGE', 'VIDEO', 'AUDIO') NOT NULL,
     url VARCHAR(255) NOT NULL,
     caption VARCHAR(255),
     creation_time DATETIME NOT NULL,
     FOREIGN KEY (trail_id) REFERENCES trail(id),
     FOREIGN KEY (stop_id) REFERENCES route_stop(id)
 );

-- Data generated by AI

INSERT INTO location (latitude, longitude, full_address, created_at) VALUES
(53.3444, -6.2574, 'Trinity College, Dublin', '2023-01-15 10:00:00'),
(51.8979, -8.4706, 'English Market, Cork', '2023-02-20 11:30:00'),
(53.2704, -9.0538, 'Spanish Arch, Galway', '2023-03-10 09:15:00'),
(52.6694, -8.6242, 'King John''s Castle, Limerick', '2023-04-05 14:20:00'),
(52.2605, -7.1062, 'Reginald''s Tower, Waterford', '2023-05-12 16:45:00'),
(52.0166, -9.5016, 'Muckross House, Killarney', '2023-06-18 08:00:00'),
(52.9726, -9.4291, 'O''Brien''s Tower, Cliffs of Moher', '2023-07-22 13:10:00'),
(53.8010, -9.5240, 'Westport House, Westport', '2023-08-30 10:30:00'),
(52.1394, -10.2740, 'Dingle Marina, Dingle', '2023-09-14 12:00:00'),
(54.3650, -8.4730, 'Benbulben, Sligo', '2023-10-01 15:00:00');

INSERT INTO route_stop (route_name, location_id, created_at) VALUES
('Trinity College', 1, '2023-01-16 09:00:00'),
('English Market', 2, '2023-02-21 10:30:00'),
('Spanish Arch', 3, '2023-03-11 08:45:00'),
('King John''s Castle', 4, '2023-04-06 13:15:00'),
('Reginald''s Tower', 5, '2023-05-13 11:20:00'),
('Muckross House', 6, '2023-06-19 07:30:00'),
 ('O''Brien''s Tower', 7, '2023-07-23 14:00:00'),
('Westport House', 8, '2023-08-31 09:45:00'),
('Dingle Marina', 9, '2023-09-15 10:15:00'),
('Benbulben Viewpoint', 10, '2023-10-02 16:30:00');

INSERT INTO trail (name, description, difficulty, estimated_time) VALUES
('Wild Atlantic Way (South)', 'Scenic drive along the rugged west coast', 'Moderate', 4.0),
('Ancient East Trail', 'Explore Ireland''s historic east', 'Easy', 3.0),
('Munster Highlights', 'Visit Cork and Killarney', 'Moderate', 3.5),
('West Coast Castles', 'Castles and estates of the west', 'Easy', 2.5),
('North West Adventure', 'Discover Sligo''s Benbulben', 'Moderate', 2.0),
('Dublin City Trail', 'Walk through Dublin''s streets', 'Easy', 2.0),
('Wicklow Mountains Challenge', 'Hike in the Wicklow Mountains', 'Hard', 5.0),
('Cliffs of Moher Coastal Walk', 'Breathtaking cliffside path', 'Moderate', 2.5),
('Dingle Peninsula Walk', 'Coastal views and ancient sites', 'Moderate', 3.5),
('Slieve League Cliff Path', 'Europe''s highest sea cliffs', 'Hard', 4.0);

INSERT INTO trail_stop (trail_id, stop_id) VALUES
(1, 3),  -- Wild Atlantic Way: Spanish Arch
(1, 7),  -- Wild Atlantic Way: O'Brien's Tower
(1, 9),  -- Wild Atlantic Way: Dingle Marina
(2, 1),  -- Ancient East: Trinity College
(2, 5),  -- Ancient East: Reginald's Tower
(3, 2),  -- Munster Highlights: English Market
(3, 6),  -- Munster Highlights: Muckross House
(4, 4),  -- West Coast Castles: King John's Castle
(4, 8),  -- West Coast Castles: Westport House
(5, 10); -- North West Adventure: Benbulben

INSERT INTO trail_media (trail_id, stop_id, media_type, url, caption, creation_time) VALUES
(1, 3, 'IMAGE', 'http://example.com/ireland/spanish_arch.jpg', 'Spanish Arch, Galway', '2023-01-17 10:00:00'),
(1, 7, 'IMAGE', 'http://example.com/ireland/cliffs_moher.jpg', 'O''Brien''s Tower at Cliffs of Moher', '2023-01-18 11:30:00'),
(2, 1, 'IMAGE', 'http://example.com/ireland/trinity_college.jpg', 'Trinity College Library', '2023-02-22 14:15:00'),
(2, 5, 'IMAGE', 'http://example.com/ireland/reginalds_tower.jpg', 'Reginald''s Tower, Waterford', '2023-02-23 09:45:00'),
(3, 2, 'IMAGE', 'http://example.com/ireland/english_market.jpg', 'English Market, Cork', '2023-03-12 07:20:00'),
(3, 6, 'AUDIO', 'http://example.com/ireland/muckross_lake.ogg', 'Birds and water at Muckross Lake', '2023-03-13 08:10:00'),
(4, 4, 'IMAGE', 'http://example.com/ireland/king_john_castle.jpg', 'King John''s Castle, Limerick', '2023-05-14 06:30:00'),
(5, 10, 'VIDEO', 'http://example.com/ireland/benbulben.mp4', 'Hiking near Benbulben', '2023-09-16 13:00:00'),
(6, NULL, 'IMAGE', 'http://example.com/ireland/dublin_street.jpg', 'Busy street in Dublin', '2023-06-20 19:45:00'),
(7, NULL, 'IMAGE', 'http://example.com/ireland/wicklow_mountains.jpg', 'View of Wicklow Mountains', '2023-04-07 12:30:00');